import type { BoardSnapshot, BoardTask, TaskStatus } from "./types";

const now = "2026-08-24T08:30:00+00:00";

function task(
  ref: number,
  title: string,
  status: TaskStatus,
  detail: string,
  extra: Partial<BoardTask> = {},
): BoardTask {
  return {
    ref,
    title,
    detail,
    accept: null,
    status,
    priority: 2,
    owner: "我",
    gate: false,
    branch: null,
    pr: null,
    repositories: [{ name: "taskboard", path: "/Users/demo/taskboard" }],
    agent_runs: [],
    blocked_by: [],
    open_blockers: [],
    blocks: [],
    actionable: status === "todo" || status === "active",
    created_at: now,
    first_started_at: status === "active" ? now : null,
    updated_at: now,
    ...extra,
  };
}

export const demoSnapshot: BoardSnapshot = {
  generated_at: now,
  db: "~/.taskboard/board.db",
  projects: [
    {
      key: "taskboard",
      name: "任务看板工具迭代",
      repo: null,
      repositories: [{ name: "taskboard", path: "/Users/demo/taskboard" }],
      summary: "让 Agent 可以更换；当前主线 #26，交互原则见 [172]，Markdown 支持见 #12。",
      artifact_url: null,
      archived: false,
      counts: { todo: 4, active: 1, waiting: 1, done: 2, dropped: 0 },
      waiting: [22],
      gates: [22],
      tasks: [
        task(
          26,
          "验证 Tauri + Vue 桌面只读 POC",
          "active",
          "**目标**：保留 Python CLI 与 SQLite，用 Vue 重做桌面展示层。\n\n- 接入真实 `board export --json`\n- 验证搜索、折叠和启动速度\n- 交互口径参照 [172]~[175]",
          {
            priority: 0,
            branch: "codex/tauri-vue-poc",
            accept: "**小批量验收（真实链路）**：\n\n- 连续多个窗口的数据可完整导出，审计列与分层计数齐全。\n- 查询结果与严格截止时间口径一致，异常状态不能进入成功终态。\n\n**大批量验收（容量与故障边界）**：\n\n- 批次满足容量、唯一性和时间边界，超时后停止提交并保留未提交计数。",
          },
        ),
        task(
          24,
          "进行中任务优先展开可执行项",
          "todo",
          "多项进行中任务只完整展开最高优先级的一项，其余保持紧凑。",
          { branch: "codex/swift-menubar-app", priority: 1 },
        ),
        task(
          31,
          "统一任务详情的优先级事实",
          "todo",
          "数据库、CLI、导出和桌面界面共用 P0–P3。",
          { priority: 1 },
        ),
        task(
          27,
          "补齐紧凑视口下的键盘导航",
          "todo",
          "确保折叠摘要、优先级菜单和任务行都能通过键盘操作。",
          { priority: 2 },
        ),
        task(
          32,
          "整理后续可延后的视觉细节",
          "todo",
          "只记录不影响主流程的微调项。",
          { priority: 3 },
        ),
        task(
          22,
          "发布 Homebrew tap 安装链路",
          "waiting",
          "等待公开发布目标与签名策略确认。",
          { gate: true, actionable: false, priority: 1 },
        ),
        task(18, "交付原生 Swift 菜单栏 App", "done", "无需常驻 HTTP 服务。", {
          owner: "双方",
          actionable: false,
        }),
        task(12, "支持安全 Markdown 正文", "done", "渲染受限 Markdown 子集。", {
          actionable: false,
        }),
      ],
      findings: [
        {
          id: 188,
          project: "taskboard",
          kind: "finding",
          category: "产品结构",
          title: "一级导航按需求组织，仓库作为关联标签",
          body: [
            "需求是持续推进的工作流；仓库用于过滤、定位和记录交付证据。",
            "",
            "| 对象 | 一级实体 | 交付坐标 |",
            "| --- | --- | --- |",
            "| 工作流 | **需求** | 仓库 |",
            "| 执行 | 任务 | `codex/tauri-vue-poc · release/taskboard-desktop` |",
          ].join("\n"),
          metric: "6 个需求 · 0 条任务缺仓库",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 170,
          project: "taskboard",
          kind: "finding",
          category: "macOS App",
          title: "状态胶囊已接入原生修改",
          body: "状态变更仍统一经过 `board` CLI，避免界面复制业务规则。",
          metric: "74 passed",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 171,
          project: "taskboard",
          kind: "finding",
          category: "数据口径",
          title: "SQLite 是任务状态的单一事实源",
          body: "桌面端只通过受限 bridge 读取和修改看板。",
          metric: "1 个 board.db",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 172,
          project: "taskboard",
          kind: "finding",
          category: "产品结构",
          title: "需求导航保留置顶、拖动和任务定位",
          body: "视图偏好写入数据库旁的 sidecar。",
          metric: "order + pinned",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 173,
          project: "taskboard",
          kind: "finding",
          category: "发布协同",
          title: "桌面构建与 CLI 发布保持独立",
          body: "未签名桌面产物不进入正式 cask。",
          metric: "release build",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 174,
          project: "taskboard",
          kind: "finding",
          category: "macOS App",
          title: "WebView 权限按命令白名单开放",
          body: "前端不能传入任意本地路径或任意 shell 参数。",
          metric: "capabilities",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 175,
          project: "taskboard",
          kind: "finding",
          category: "macOS App",
          title: "三档视口与原生 release 构建共同验收",
          body: "浏览器交互通过不等同于原生窗口验证。",
          metric: "375/1440/1600",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 176,
          project: "taskboard",
          kind: "finding",
          category: "数据口径",
          title: "长标题 Sheet 仍需保持完整可达",
          body: "密集分类用于验证桌面端横向滚动与两端导航按钮。",
          metric: "11 Sheet",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
        {
          id: 177,
          project: "taskboard",
          kind: "finding",
          category: "数据口径",
          title: "演示数据覆盖真实分类密度",
          body: "避免只用少量短标题通过视觉验收。",
          metric: "dense tabs",
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
      ],
      risks: [
        {
          id: 189,
          project: "taskboard",
          kind: "risk",
          category: "发布协同",
          title: "多仓库完成证据仍缺少逐仓库 artifacts",
          body: "当前完成事件只有一个提交坐标，后续需要逐仓库交付证据。",
          metric: null,
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
      ],
      links: [
        {
          id: 191,
          project: "taskboard",
          kind: "link",
          category: "macOS App",
          title: "apps/desktop",
          body: "Tauri + Vue 桌面端实现入口。",
          metric: null,
          created_at: now,
          updated_at: now,
          superseded_by: null,
          superseded_at: null,
          supersedes: [],
          is_superseded: false,
          settled_at: null,
          is_settled: false,
        },
      ],
      concepts: [
        {
          id: 330,
          project: "taskboard",
          category: null,
          title: "对齐失效由锚点提交现算,不落状态列",
          body: "存 stale 列就要在每次提交后回写,漏一次状态就和代码脱节。改成读时用 aligned_commit + 锚点路径跑一次 git log 推导,状态永远等于当前事实。",
          repository: "taskboard",
          repository_path: "/Users/demo/taskboard",
          task_ref: 26,
          task_project: "taskboard",
          files: [
            { repository: "taskboard", repository_path: "/Users/demo/taskboard", path: "taskboard/store.py", symbol: "_concept_state" },
            { repository: "taskboard", repository_path: "/Users/demo/taskboard", path: "taskboard/gitref.py", symbol: "moved_anchors" },
          ],
          moved: [],
          state: "proposed",
          aligned_at: null,
          aligned_commit: null,
          rejected_at: null,
          created_at: now,
        },
        {
          id: 327,
          project: "taskboard",
          category: null,
          title: "概念对齐的归属单位是仓库,不是需求",
          body: "同一仓库被多个需求共用时,概念只解释一遍。",
          repository: "taskboard",
          repository_path: "/Users/demo/taskboard",
          task_ref: null,
          task_project: null,
          files: [
            { repository: "taskboard", repository_path: "/Users/demo/taskboard", path: "taskboard/store.py", symbol: "concepts" },
          ],
          moved: ["taskboard/store.py:concepts"],
          state: "stale",
          aligned_at: now,
          aligned_commit: "c8fe214",
          rejected_at: null,
          created_at: now,
        },
        {
          id: 24,
          project: "taskboard",
          category: "方法论",
          title: "用户是一个人+一个 AI,不是团队",
          body: "拒绝 5 类经典团队功能:权限、评论流、通知、多人指派、燃尽图。",
          repository: null,
          repository_path: null,
          task_ref: null,
          task_project: null,
          files: [],
          moved: [],
          state: "aligned",
          aligned_at: now,
          aligned_commit: null,
          rejected_at: null,
          created_at: now,
        },
        {
          id: 12,
          project: "taskboard",
          category: null,
          title: "看板需要实时协同",
          body: "曾提议 WebSocket 推送。",
          repository: "taskboard",
          repository_path: "/Users/demo/taskboard",
          task_ref: null,
          task_project: null,
          files: [],
          moved: [],
          state: "rejected",
          aligned_at: null,
          aligned_commit: null,
          rejected_at: now,
          created_at: now,
        },
      ],
      updated_at: now,
    },
    {
      key: "reg-calibration",
      name: "注册风控模型校准",
      repo: null,
      repositories: [
        { name: "coinex_backend", path: "/Users/demo/coinex_backend" },
        { name: "coinex_anti_fraud_service", path: "/Users/demo/coinex_anti_fraud_service" },
      ],
      summary: "跨仓库推进取数、训练、导出与发布验收。",
      artifact_url: null,
      archived: false,
      counts: { todo: 2, active: 0, waiting: 0, done: 7, dropped: 0 },
      waiting: [],
      gates: [],
      tasks: [
        task(27, "第二步：配比抽样与概率校准", "todo", "按冻结名单完成概率校准。"),
        task(16, "按 plan_only 名单补录事实", "todo", "替代旧名单并补齐事实快照。"),
      ],
      findings: [],
      risks: [],
      links: [],
      concepts: [],
      updated_at: now,
    },
  ],
};
